CREATE DATABASE IF NOT EXISTS `travelhub`;

USE `travelhub`;

CREATE TABLE IF NOT EXISTS `afisha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `image` VARCHAR(100) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`)
);